version: '3'
services:
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: clean-arch-example-db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=clean-arch-example
      - MYSQL_DATABASE=clean-arch-example
      - MYSQL_USER=clean-arch-example
      - MYSQL_PASSWORD=clean-arch-example
  api:
    build: .
    container_name: clean-arch-example-api
    ports:
      - 8080:8080
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    tty:
      true
    depends_on:
      - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: clean-arch-example-phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    links:
      - db
    ports:
      - 8888:80
    volumes:
      - /sessions