[[constraint]]
  name = "github.com/go-chi/chi"
  version = "3.3.1"

[[constraint]]
  branch = "master"
  name = "github.com/swaggo/http-swagger"

[[constraint]]
  name = "github.com/swaggo/swag"
  version = "1.3.2"
